version: '3'
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

  odoo11:
    image: odoo:11
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    # command: odoo scaffold /mnt/extra-addons/MODULE_NAME
    volumes:
      - ./odoo_addons:/mnt/extra-addons
      - ./odoo_etc:/etc/odoo
volumes:
  db:
  odoo11:
